#!/bin/bash

git checkout dev
git add -A
git commit -am "$1"

git push origin dev

pushtomaster(){
  echo '> PUSHING TO MASTER >>>'
  git checkout master
  git merge dev
  git push origin master
  git checkout dev
  echo '>>>>> PUSHING TO MASTER |'
}

[[ "$2" == "m" ]] && pushtomaster
