#!/bin/bash

echo '> PUSHING TO DEV >>>'
git checkout dev
git add -A
git commit -am "$1"
git push origin dev
echo '>>>>> PUSHING TO DEV |'

pushtomaster(){
  echo '> PUSHING TO MASTER >>>'
  git checkout master
  git merge dev
  git push origin master
  git checkout dev
  echo '>>>>> PUSHING TO MASTER |'
}

[[ "$2" == "m" ]] && pushtomaster
