#!/bin/bash

git checkout dev
git add -A
git commit -am "$1"

git push origin dev

pushtomaster(){
  echo 'p'
  # git checkout master
  # git merge dev
  # git push origin master
  # git checkout dev
}

echo 'run'
[[ "$2" === "m" ]] && pushtomaster
